### ISSUE TITLE
consider Reconcile method in Deployable interface

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/naml#10]
this seems like defining a reconcile when you define an app makes sense? maybe i’m crazy?

**Comment by arschles** [comment]
seems like it would work well for #6. another place it might come in handy could be to un-f*ck your installation without doing a full delete-reinstall?

**Comment by jdef** [comment]
Would this be useful for upgrades, or should there be an Upgradable interface for that?

**Comment by jdef** [comment]
Maybe install should be smart enough to Do The Right Thing, and so no need for interfaces for reconcile or update?

**Comment by kris-nova** [comment]
Closed with https://github.com/kris-nova/naml/releases/tag/1.0.0
