### ISSUE TITLE
consider Validate() or Test() methods in Deployable interface 

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/naml#11]
i’m not convinced this is a good idea yet - writing down before i forget

**Comment by arschles** [comment]
what about separate interfaces (`DeployableValidater`? `DeployableTester`?) that you can optionally implement and if you do, those functions will be called

**Comment by kris-nova** [comment]
Closed with https://github.com/kris-nova/naml/releases/tag/1.0.0
