### ISSUE TITLE
New name for the project

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/naml#16]
Looks like this is not the best name. We should find a better name. 

Any suggestions?

**Comment by kris-nova** [comment]
please upvote for `nahml`

**Comment by tylerdave** [comment]
`ube` or `purpleyam`. Awesome color + also known as "greater yam" 🤷

**Comment by pratikbalar** [comment]
`purpleyeml`

**Comment by bbaassssiiee** [comment]
gotcha

**Comment by rubensa** [comment]
**YAGoKu** - Yet Another Go Kubernetes
or simply
**GoKu** - Go Kubernetes (some ideas for the mascot based on this name ;P )
