### ISSUE TITLE
Make this a GitHub template repo?

### ISSUE THREAD

**Issue by arschles** [kris-nova/naml#21]
If I understand properly, you're supposed to fork this repo and then modify it to fit your app. GH templates would make it a little bit easier for folks to do that.

**Comment by arschles** [comment]
another idea could be to split this out into an example repo and the code libraries (the stuff in `pkg/`). that way, people could either write their own CLI stuff and opt-in to your libraries, or they can use your full codebase and get a full working everything in a click

**Comment by kris-nova** [comment]
> another idea could be to split this out into an example repo and the code libraries (the stuff in pkg/). that way, people could either write their own CLI stuff and opt-in to your libraries, or they can use your full codebase and get a full working everything in a click

yes. i'm sold.

**Comment by kris-nova** [comment]
examples can be merged here: https://github.com/naml-examples

@arschles i made you an organization owner so you should be able to manage the org of examples as well

we need

 - stateful apps
 - controller/operator
 - custom CLI

**Comment by kris-nova** [comment]
simple repo has been ported https://github.com/naml-examples/simple

**Comment by arschles** [comment]
what do you mean by stateful apps?
