### ISSUE TITLE
Need more complex example

### ISSUE THREAD

**Issue by kokizzu** [kris-nova/naml#33]
eg. setup redis, postgresql/mysql, and one dummy golang app that connect both

**Comment by kris-nova** [comment]
would having an example of nivenly.com with naml help you out?

**Comment by kokizzu** [comment]
yup sure

**Comment by kris-nova** [comment]
okay ill push a change and update this issue as soon as i can

**Comment by derrickburns** [comment]
The "full" example link is broken.

**Comment by kris-nova** [comment]
Please see the latest feature ˚naml codify` in [release 0.2.2](https://github.com/kris-nova/naml/releases/tag/0.2.2)

This should let you pass an entire namespace to `naml codify` to generate whatever application you want

```bash 
kubectl get all -n mynamespace | naml codify > main.go
```

If there are any applications anyone wants to see - we can certainly add them to [naml-examples](https://github.com/naml-examples)
