### ISSUE TITLE
race condition in naml stuffs

### ISSUE THREAD

**Issue by mauilion** [kris-nova/naml#56]
./naml -f sample/sample.naml list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46e8a2]

goroutine 1 [running]:
github.com/kris-nova/naml.AddRPC(0xc0001d91a0, 0x12, 0xc0004f1c90, 0x1)
	/home/dcooley/git/naml/rpc.go:303 +0x514
github.com/kris-nova/naml.AllInit(0x18fd24b, 0xe, 0x0, 0xc0004f1b10, 0x1, 0x1, 0xc0004f1c00, 0xc0004f1c20)
	/home/dcooley/git/naml/cmd.go:353 +0x1fd
github.com/kris-nova/naml.RunCommandLineWithOptions.func5(0xc000558040, 0x1, 0x1)
	/home/dcooley/git/naml/cmd.go:285 +0x65
github.com/urfave/cli/v2.(*Command).Run(0xc00040d9e0, 0xc00047bf80, 0x0, 0x0)
	/home/dcooley/git/naml/vendor/github.com/urfave/cli/v2/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc000261ba0, 0x1af9dd0, 0xc0001b4320, 0xc0001bc000, 0x4, 0x4, 0x0, 0x0)
	/home/dcooley/git/naml/vendor/github.com/urfave/cli/v2/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
	/home/dcooley/git/naml/vendor/github.com/urfave/cli/v2/app.go:224
github.com/kris-nova/naml.RunCommandLineWithOptions(0x408005, 0xc000182058)
	/home/dcooley/git/naml/cmd.go:316 +0xf2b
github.com/kris-nova/naml.RunCommandLine(...)
	/home/dcooley/git/naml/cmd.go:51
github.com/kris-nova/naml.RunCommandLineAndExit()
	/home/dcooley/git/naml/cmd.go:39 +0x25
main.main()
	/home/dcooley/git/naml/cmd/main.go:30 +0x25

**Comment by kris-nova** [comment]
just run naml in rpc mode a bunch

**Comment by kris-nova** [comment]
i think we just need to write a small system to hang for the rpc connection at runtime
