### ISSUE TITLE
Promote @fkautz to maintainer

### ISSUE THREAD

**Issue by kris-nova** [kris-nova/naml#58]
This project seems to have seen decent traction - perhaps it's worth considering another maintainer?

Anyway @fkautz you seem to be the most active here. Would you be interested in a low-commitment maintainer spot on the project to serve as another place to get things done / merge PRs / review my code / etc?

**Comment by fkautz** [comment]
Sure, I'd be happy to help.

**Comment by kris-nova** [comment]
Welcome aboard: the world is ours to craft. https://github.com/kris-nova/naml/invitations
